# Hypothesis testing

## General concepts
Hypothesis testing provides an objective framework for making decisions using probabilistic methods, rather than relying on subjective impressions.  In a **one-sample problem**, hypotheses are specified about a single distribution; in a **two-sample problem**, two different distributions are compared.

The **null hypothesis** (${H_0}$) is the hypothesis that is to be tested.  The **alterantive hypothesis** (${H_1}$) is the hypothesis that contradicts the null hypothesis.  If ${H_0}$ is true and ${H_0}$ is accepted, or if ${H_0}$ is true and ${H_1}$ is rejected, then the correct decision has been made.  If ${H_0}$ is true and ${H_0}$ is rejected, or if ${H_1}$ is true and ${H_0}$ is accepted, then an error has been made.  A **type I error** occurs when rejecting the null hypothesis when the alternative hypothesis is true (false positive).  A **type II error** occurs when accepting the null hypothesis when the alternative hypothesis is true (false negative).

The probability of a type I error is also referred to as the **signfiance level** ${\alpha}$.  The probability of a type II error is denoted by ${\beta}$.  The **power** of a test is the probability that the test correctly rejects the null hypothesis when the alternative hypothesis is true and is defined as ${1-\beta}$.

The general aim in hypothesis testing is to use statistical tests that make ${\alpha}$ and ${\beta}$ as small as possible.  This goal requires compromise because making ${\alpha}$ small involves rejecting the null hypothesis less often, whereas making ${\beta}$ small involves accepting the null hypothesis less often.  That is, as ${\alpha}$ decreases, ${\beta}$ increases.  Our general strategy is to fix ${\alpha}$ at some specific level (e.g. 0.05) and to use the test that minimizes ${\beta}$ or, equivalently, maximizes the power.

A **one-tailed test** is a test in which the values of the parameter being studied under the alternative hypothesis are allowed to be either greater than or less than the values of the parameter under the null hypothesis, *but not both*.  A **two-tailed test** is a test in which the values of the parameter being studies under the alternative hypothesis are allowed to be either greater than or less than the values of the parameter under the null hypothesis. A two-tailed test would be preferred over a one-tailed test if no prior knowledge is available about the direction of the alternative hypothesis if the null hypothesis is rejected.  However, in certain situations only alternatives on one side of the null mean are of interest or are possible, and in this case a one-sided test is better because it has more power (that is, it is easier to reject the null hypothesis).  *It is important to decide weather to use a one-sided or two-sided test before data analysis so as to not bias the conclusions.*

A **p-value** or probability value is the probability for a given statistical model that, when the null hypothesis is true, the statistical summary (such as the sample mean difference between two compared groups) would be the same as or of greater magnitude than the actual observed results.  A p < 0.05 is generally accepted as significant.